version: "3.6"
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
        SPRING_DATA_MONGODB_HOST: mongodb
        SPRING_DATA_MONGODB_PORT: 27017
        SPRING_DATA_MONGODB_DB: test
    links:
      - mongodb
    depends_on:
      - mongodb
    hostname: api

  mongodb:
    image: mongo:4
    volumes:
        - mongo_data:/data/db
    ports:
        - 27017:27017
    hostname: mongodb


volumes:
    mongo_data: {}